apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-existing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi 
  volumeName: jenkins-old-ebs-pv
  storageClassName: ""
